# -*- coding: utf-8 -*-
"""split_chromosome.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bKhP4IoDjFWjmPef-NK3wqhiXS0g4oR-
"""

#for each cell, split the atac into different chromosome
def split_chrom(adata_atac):
  row_name=adata_atac.var.index
  chrom_name=[c.split("-")[0] for c in row_name]
  
  lst=np.unique(chrom_name)#names for chromosome

  chrom_index=dict()
  for i in range(len(lst)):
    index = [a for a, l in enumerate(chrom_name) if l==lst[i]]
    if lst[i] not in chrom_index:
      chrom_index[lst[i]]=index

  return chrom_index